version: '3.9'
services:
  ai-intern-assessment:
    build: .
    container_name: ambitio_ai_platform
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - CHROMA_PERSIST_DIR=${CHROMA_PERSIST_DIR}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - .:/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
